name: Find Duplicate Tracks

on:
  workflow_dispatch: {}

jobs:
  dupes:
    uses: ./.github/workflows/playlist-tool.yml
    with:
      # SOFT, SOFT_ADDS, TVEKSAMT
      args: "--cmd dupes --source 7xUa8Da5yH2PrFwLpPgAJr --source 0eHnbTUBCBaDVXibzCSymN --source 4SNjbtv34S4Ra7TMNTnERL"
