name: Find Duplicate Tracks

on:
  workflow_dispatch: {}

jobs:
  dupes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run duplicates report
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          DUPES_PLAYLIST_IDS: ${{ secrets.DUPES_PLAYLIST_IDS }} # space- or comma-separated IDs
        run: |
          if [ -z "$DUPES_PLAYLIST_IDS" ]; then
            echo "DUPES_PLAYLIST_IDS secret is not set. Set it to a list of playlist IDs (comma- or space-separated)."
            exit 1
          fi
          IDS=$(echo "$DUPES_PLAYLIST_IDS" | tr ',' ' ')
          echo "Running duplicates report for IDs: $IDS"
          node playlist-tool.js dupes $IDS

